language: python
python:
  - 2.7
  - 3.6
  - 3.7
matrix:
  include:
    - python: 3.7
      env: TOXENV=docs
install:
  - pip install tox-travis
  - pip install sphinx
script:
  - tox

branches:
  only:
  - master
